modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/ochotonida/caldera/issues"
license="MIT"

[[mods]]
modId = "caldera"
version = "1.18.1-0.0.0"
displayName = "Caldera"
displayURL="https://www.curseforge.com/minecraft/mc-mods/caldera"
# logoFile = "logo.png"
description = '''Magic much'''

[[dependencies.caldera]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.caldera]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"